apiVersion: v1
kind: Service
metadata:
  name: turn-server
  namespace: bro-media
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: turn-server
  ports:
    - name: turn-udp
      port: 3478
      targetPort: 3478
      protocol: UDP
    - name: turn-tcp
      port: 3478
      targetPort: 3478
      protocol: TCP
    - name: turns-tcp
      port: 5349
      targetPort: 5349
      protocol: TCP
    - name: relay-49160
      port: 49160
      targetPort: 49160
      protocol: UDP
    - name: relay-49161
      port: 49161
      targetPort: 49161
      protocol: UDP
    - name: relay-49162
      port: 49162
      targetPort: 49162
      protocol: UDP
    - name: relay-49163
      port: 49163
      targetPort: 49163
      protocol: UDP
    - name: relay-49164
      port: 49164
      targetPort: 49164
      protocol: UDP
    - name: relay-49165
      port: 49165
      targetPort: 49165
      protocol: UDP
    - name: relay-49166
      port: 49166
      targetPort: 49166
      protocol: UDP
    - name: relay-49167
      port: 49167
      targetPort: 49167
      protocol: UDP
    - name: relay-49168
      port: 49168
      targetPort: 49168
      protocol: UDP
    - name: relay-49169
      port: 49169
      targetPort: 49169
      protocol: UDP
